#############################################################################
#
# Modified version of jekyllrb Rakefile
# https://github.com/jekyll/jekyll/blob/master/Rakefile
#
#############################################################################

require 'rake'
require 'yaml'

namespace :site do
	desc "Generate the site and push changes to remote origin"
	task :deploy do
		
		CONFIG = YAML.load(File.read('_config.yml'))
        DEST_DIR = CONFIG["destination"]
		
		# Detect pull request
		if ENV['TRAVIS_PULL_REQUEST'].to_s.to_i > 0
			puts 'Pull request detected. Not proceeding with deploy.'
			exit
		end

		# Make sure destination folder exists as git repo
		sh("git clone https://$GH_USER:$GH_TOKEN@github.com/$GH_USER/$GH_USER.github.io.git #{DEST_DIR}")

		# Generate the site
		sh("bundle exec jekyll build")

		# Commit and push to github
		commit_log = `git log -1 --pretty=format:"%s"`
		Dir.chdir(DEST_DIR) do
			
			commit_user = "#{ENV['GH_NAME']}"
			if commit_user.length < 1
				commit_user = "#{ENV['GH_USER']}"
			end
				
			sh("git config user.name #{commit_user}")
			sh("git config user.email #{ENV['GH_EMAIL']}")
			sh("git config push.default simple")
			
			sh("git add --all .")
			sh("git commit -m '#{commit_log}'")
			sh("git push")
		end
	end
end
